config/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name= 'index'),
    path('consultas/', consulta, name ='consultas'),
]

app/models.py
from django.db import models

# Create your models here.
class Funcoes(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Pessoa(models.Model):
    nome = models.CharField(max_length=50)
    funcao = models.ForeignKey(Funcoes,on_delete=models.CASCADE)
    pais_de_origem = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.nome} {self.funcao} {self.pais_de_origem}'

class Banda(models.Model):
    nome = models.CharField(max_length=50)
    pais_de_origem = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.nome} {self.pais_de_origem}'

class Genero(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Biagrafia(models.Model):
    historia = models.CharField(max_length=2000)
    banda = models.ForeignKey(Banda,on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.historia} {self.banda}'
class Album(models.Model):
    nome = models.CharField(max_length=50)
    banda = models.ForeignKey(Banda,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nome} {self.banda}' 

class Musica(models.Model):
    nome = models.CharField(max_length=50)
    letra_da_musica = models.TextField(max_length=2000)
    genero = models.ForeignKey(Genero,on_delete=models.CASCADE)
    interprete = models.ForeignKey(Pessoa,related_name='interprete',on_delete=models.CASCADE)
    compositor = models.ForeignKey(Pessoa,related_name='compositor',on_delete=models.CASCADE)
    ano_de_lancamento = models.CharField(max_length=50)
    album = models.ForeignKey(Album,on_delete=models.CASCADE)


    def __str__(self):
        return f'{self.nome} {self.letra_da_musica} {self.genero} {self.interprete} {self.compositor} {self.ano_de_lancamento}'

app/forms.py
from django import forms
from .models import *

# inicializando um formulario para os Albuns
class MusicaForm(forms.ModelForm):
    class Meta:
        # modelo referente: Album
        model = Musica
        # atribuindo todos os campos do modelo Book ao Form
        fields = '__all__'


class AlbumForm(forms.ModelForm):
    class Meta:
        # modelo referente: Album
        model = Album
        # atribuindo todos os campos do modelo Book ao Form
        fields = '__all__'

app/views.py
from django.shortcuts import render
from . models import*

# Create your views here.
def consulta (request):
    consultas ={
        'consultas':Musica.objects.all()
    }

    return render(request, 'consultas/consultas.html', consultas)




app/templates/consultas/consultas.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Página Inicial</title>
  <!-- Incluindo Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="bg-ligth"> <!-- Adicionando a classe bg-primary para definir a cor de fundo -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/">Acervo Musical</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/consultas/">Consulta</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>
  <style>
    #id_letra_da_musica {
    height: 400px; /* Defina o tamanho desejado para a caixa de texto */
}
  </style>

  <div class="container mt-5">
    <h2 class="mb-4">Tabela de Músicas</div></h2>
        <table class="table">
            <thead>
                 <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Letra da Música</th>
                    <th scope="col">Gênero</th>
                    <th scope="col">Interprete</th>
                    <th scope="col">Compositor</th>
                    <th scope="col">Ano de Lançamento</th>
                    <th scope="col">Album</th>
                 </tr>
                 {% for Musica in consultas %}
             </thead>
             </tbody>
              <td>{{Musica.nome}} </td>
              <td>
                <pre>{{ Musica.letra_da_musica }}</pre>
              </td>
              <td>{{Musica.genero}} </td>
              <td>{{Musica.interprete}} </td>
              <td>{{Musica.compositor}} </td>
              <td>{{Musica.ano_de_lancamento}} </td>
              <td>{{Musica.album}} </td>
             </tbody>
              {% endfor %}
         </table>
     </div>
 </div>
</div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Página Inicial</title>
  <!-- Incluindo Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<style>
  /* Adicionando estilos para o plano de fundo */
  body {
    background-image: url('{% static "images/Figura.jpg" %}');
    background-size: cover;
    background-position: center center;
    background-repeat: no-repeat;
    height: 100vh;
  }
</style>
<body > <!-- Adicionando a classe bg-primary para definir a cor de fundo -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/">Acervo Musical</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/consultas/">Consulta</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>
  

  <div class="container mt-5">
    <div class="jumbotron text-center">
      <h1 class="display-4">Olá, é bom te ver por aqui</h1>
      <p class="lead">Esta é a página inicial do Acervo Musical</p>
      <p class="lead">Seja Bem Vindo(A)</p>
    </div>
  </div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>